updates:
- assignees:
  - bobgy
  - jlewi
  directory: notebook_testing
  open-pull-requests-limit: 10
  package-ecosystem: docker
  reviewers:
  - Jeffwan
  - pingsutw
  schedule:
    interval: daily
- assignees:
  - bobgy
  - jlewi
  directory: test-infra/auto-deploy
  open-pull-requests-limit: 10
  package-ecosystem: docker
  reviewers:
  - Jeffwan
  - pingsutw
  schedule:
    interval: daily
- assignees:
  - bobgy
  - jlewi
  - PatrickXYS
  directory: images
  open-pull-requests-limit: 10
  package-ecosystem: docker
  schedule:
    interval: daily
- assignees:
  - bobgy
  - jlewi
  directory: apps-cd
  open-pull-requests-limit: 10
  package-ecosystem: docker
  reviewers:
  - Jeffwan
  - pingsutw
  schedule:
    interval: daily
- assignees:
  - bobgy
  - jlewi
  directory: go
  open-pull-requests-limit: 10
  package-ecosystem: docker
  reviewers:
  - Jeffwan
  - pingsutw
  schedule:
    interval: daily
- assignees:
  - bobgy
  - jlewi
  directory: .
  open-pull-requests-limit: 10
  package-ecosystem: npm
  reviewers:
  - Jeffwan
  - pingsutw
  schedule:
    interval: daily
- assignees:
  - bobgy
  - jlewi
  - PatrickXYS
  directory: py/kubeflow/testing/node-license-tools
  open-pull-requests-limit: 10
  package-ecosystem: npm
  schedule:
    interval: daily
- assignees:
  - bobgy
  - jlewi
  directory: test-infra/auto-deploy
  open-pull-requests-limit: 10
  package-ecosystem: pip
  reviewers:
  - Jeffwan
  - pingsutw
  schedule:
    interval: daily
- assignees:
  - bobgy
  - jlewi
  directory: apps-cd
  open-pull-requests-limit: 10
  package-ecosystem: pip
  reviewers:
  - Jeffwan
  - pingsutw
  schedule:
    interval: daily
- assignees:
  - bobgy
  - jlewi
  directory: py
  open-pull-requests-limit: 10
  package-ecosystem: pip
  reviewers:
  - Jeffwan
  - pingsutw
  schedule:
    interval: daily
- assignees:
  - bobgy
  - jlewi
  - PatrickXYS
  directory: py/kubeflow/testing
  open-pull-requests-limit: 10
  package-ecosystem: pip
  schedule:
    interval: daily
- assignees:
  - bobgy
  - jlewi
  directory: go
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - Jeffwan
  - pingsutw
  schedule:
    interval: daily
- assignees:
  - bobgy
  - jlewi
  directory: go/cmd/nomos-wait
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - Jeffwan
  - pingsutw
  schedule:
    interval: daily
- assignees:
  - bobgy
  - jlewi
  directory: tests
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - Jeffwan
  - pingsutw
  schedule:
    interval: daily
version: 2
